{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getException"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/GraalException","preciseIdentifier":"s:15DXFeedFramework14GraalExceptionO","text":"GraalException"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["macOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"GraalException. Rethrows exception from Java."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dxfeedframework\/promise\/getexception()"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Promise\/getException()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Returns exceptional outcome of computation. If computation has no  "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Promise\/hasException()"},{"type":"text","text":" exception,"},{"type":"text","text":" "},{"type":"text","text":"then this method returns "},{"type":"codeVoice","code":"nil"},{"type":"text","text":". If computation has completed exceptionally or was cancelled, then"},{"type":"text","text":" "},{"type":"text","text":"the result of this method is not "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"If computation was "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Promise\/isCancelled()"},{"type":"text","text":" cancelled, then this method returns an"},{"type":"text","text":" "},{"type":"text","text":"instance of GraalException."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getException"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"GraalException","preciseIdentifier":"s:15DXFeedFramework14GraalExceptionO"},{"kind":"text","text":"?"}],"title":"getException()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"s:15DXFeedFramework7PromiseC12getExceptionAA05GraalE0OSgyF","modules":[{"name":"DXFeedFramework"}]},"hierarchy":{"paths":[["doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Promise"]]},"references":{"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/Promise/isCancelled()":{"role":"symbol","title":"isCancelled()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isCancelled"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Returns "},{"type":"strong","inlineContent":[{"type":"text","text":"true"}]},{"type":"text","text":" when computation was canceled."},{"type":"text","text":" "},{"type":"text","text":"Use "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Promise\/getException()"},{"type":"text","text":" method to get the corresponding exception."}],"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Promise\/isCancelled()","kind":"symbol","type":"topic","url":"\/documentation\/dxfeedframework\/promise\/iscancelled()"},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/Promise":{"role":"symbol","title":"Promise","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Promise"}],"abstract":[{"type":"text","text":"Result of a computation that will be completed normally or exceptionally in the future."},{"type":"text","text":" "},{"type":"text","text":"This class is designed to represent a promise to deliver certain result."}],"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Promise","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Promise"}],"url":"\/documentation\/dxfeedframework\/promise"},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/GraalException":{"role":"symbol","title":"GraalException","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"GraalException"}],"abstract":[{"type":"text","text":"Represents errors that occur when calling graal function."}],"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/GraalException","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GraalException"}],"url":"\/documentation\/dxfeedframework\/graalexception"},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/Promise/getException()":{"role":"symbol","title":"getException()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getException"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"GraalException","preciseIdentifier":"s:15DXFeedFramework14GraalExceptionO"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Returns exceptional outcome of computation. If computation has no  "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Promise\/hasException()"},{"type":"text","text":" exception,"},{"type":"text","text":" "},{"type":"text","text":"then this method returns "},{"type":"codeVoice","code":"nil"},{"type":"text","text":". If computation has completed exceptionally or was cancelled, then"},{"type":"text","text":" "},{"type":"text","text":"the result of this method is not "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"If computation was "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Promise\/isCancelled()"},{"type":"text","text":" cancelled, then this method returns an"},{"type":"text","text":" "},{"type":"text","text":"instance of GraalException."}],"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Promise\/getException()","kind":"symbol","type":"topic","url":"\/documentation\/dxfeedframework\/promise\/getexception()"},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework":{"role":"collection","title":"DXFeedFramework","abstract":[],"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework","kind":"symbol","type":"topic","url":"\/documentation\/dxfeedframework"},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/Promise/hasException()":{"role":"symbol","title":"hasException()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hasException"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Returns "},{"type":"strong","inlineContent":[{"type":"text","text":"true"}]},{"type":"text","text":" when computation has completed exceptionally or was cancelled."},{"type":"text","text":" "},{"type":"text","text":"Use "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Promise\/getException()"},{"type":"text","text":" method to get the exceptional outcome of the computation."}],"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Promise\/hasException()","kind":"symbol","type":"topic","url":"\/documentation\/dxfeedframework\/promise\/hasexception()"}}}